language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/taxi-app

node_js:  
  - "16.6.1"

  

before_script:
  - npm install
  - psql -c 'create database  taxi-app;' -U postgres
  - psql -U postgres -d taxi-app -a -f sql/tables.sql
  - psql -U postgres -d taxi-app -a -f sql/data.sql

services:
  - postgresql